Feature poc implementation
sk4zuzu/m-classic-epiphany-on-aks pull request #1
Opened 2020-10-05 17:40 UTC by sk4zuzu

2020-10-06 12:25 UTC, mkyc requested changes
Most important problem for me is that this version templates all classic epiphany configs into module config file. We should put variables in that config and template files on the fly

2020-10-06 12:25 UTC, mkyc commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +def _check_virtual_machines(documents):
```suggestion
def _check_virtual_machines_amounts(documents):
```

2020-10-06 12:25 UTC, mkyc commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +def _check_components(documents):
```suggestion
def _check_components_configuration(documents):
```

2020-10-06 12:25 UTC, mkyc commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +            auto_remove=False,
shouldn't it be `True`?

2020-10-06 12:25 UTC, mkyc commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
can you fix it?

2020-10-06 12:25 UTC, mkyc commented on tests/integration/test_plan_minimal_cluster_with_applications.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
can you fix it?

2020-10-06 12:25 UTC, mkyc commented on tests/integration/test_plan_minimal_cluster_with_applications.py
> +  config: |
OMG I just realised what you've done ..... it shouldn't be this way. We should have just values in config and template it on the fly during `plan` and `apply` phases.

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_combine.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
can you fix it?

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_dictify.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_load_yaml.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_memoize.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_select.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_sorted_dict.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_udiff.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on tests/unit/test_undictify.py
> +# pylint: disable=missing-module-docstring,missing-function-docstring
fix

2020-10-06 12:25 UTC, mkyc commented on resources/azepi/apply.py
> +            "--vault-password=" + "'asd'",
should we put it into config?

2020-10-06 12:27 UTC, sk4zuzu commented on Dockerfile
> +FROM $ARG_BASE_IMAGE
:+1: but I'd leave an option. What I implemented now is fantastic for development purposes.

2020-10-06 12:28 UTC, sk4zuzu commented on Makefile
> +	cd $(CACHE_DIR)/epiphany/ && docker build -t epicli-$(IMAGE)-develop .
Yes this is temporary, but also it's useful for development if something important went to develop. I'd keep this as an option. :innocent:

2020-10-06 12:29 UTC, sk4zuzu commented on Makefile
> +	cd $(ROOT_DIR)/ && git diff
Yes if it's OK to install linter etc inside docker image. :+1:

2020-10-06 12:30 UTC, sk4zuzu commented on README.md
> +```
This is just an example what can be executed. :thinking:

2020-10-06 12:32 UTC, sk4zuzu commented on README.md
> +```
Then execution of tests must be moved to docker container. I wanted to avoid that. :thinking:
In that case we have to rewrite whole testing solution. :(

2020-10-06 12:33 UTC, sk4zuzu commented on README.md
> +```
Oh I get it. You look at time from users perspective. I looked at it from developers perspective.

2020-10-06 12:35 UTC, sk4zuzu commented on README.md
> +In `examples/basic_flow` directory run (in order):
We don't have such functionality in Epiphany for the "any" provider.

2020-10-06 12:35 UTC, sk4zuzu commented on README.md
> +### Prepare service principal
I did this specifically to improve readability. "#" is just too big.

2020-10-06 12:36 UTC, sk4zuzu commented on examples/basic_flow/Makefile
> +		kubeconfig
What exactly is not required? :thinking:

2020-10-06 12:38 UTC, sk4zuzu commented on examples/basic_flow/Makefile
> +		kubeconfig
Ok I get it. Next comment explains it.

2020-10-06 12:39 UTC, sk4zuzu commented on pylintrc
> +disable=print-statement,
This is the default config of pylint + extra ones. I can turn this off and see what happens.

2020-10-06 12:41 UTC, sk4zuzu commented on resources/azepi/_helpers.py
> +def memoize(function):
OK I'll add a comment. :thinking:

2020-10-06 12:42 UTC, sk4zuzu commented on resources/azepi/_helpers.py
> +    # Implementation taken from Epiphany's helpers
Will be removed. :+1:

2020-10-06 12:43 UTC, sk4zuzu commented on resources/azepi/init.py
> +# Original one seems to be incorrect (05 Oct 2020)
No, I asked poeople if this is a bug. Nobody cared. :trollface:

2020-10-06 12:45 UTC, sk4zuzu commented on resources/azepi/init.py
> +def _get_dummy_machines(_, count):
Yep, can be removed. :+1:

2020-10-06 12:49 UTC, sk4zuzu commented on resources/azepi/init.py
> +        machines = _get_dummy_machines(v, 4)
No special reason. I will fix it. :+1:

2020-10-06 12:59 UTC, sk4zuzu commented on README.md
> +```
Or pass the docker socket maybe. :thinking:

2020-10-06 13:11 UTC, sk4zuzu commented on resources/azepi/init.py
> +    })
I'll verify. If this is the only use case then I'll do it for sure. Otherwise I need to think. :thinking:

2020-10-06 13:12 UTC, sk4zuzu commented on resources/azepi/init.py
> +    })
Yes, this is a bug! :fearful:

2020-10-06 13:15 UTC, sk4zuzu commented on resources/azepi/init.py
> +        del state[v["M_MODULE_SHORT"]]
Yes indeed, it should be just merged without the remove. :+1:

2020-10-06 13:16 UTC, sk4zuzu commented on tests/integration/test_init_minimal_cluster_with_applications.py
> +            auto_remove=False,
It's deleted couple of lines below. This helps with retrieving logs from the container is it fails for example.

2020-10-06 13:20 UTC, sk4zuzu commented on tests/integration/test_plan_minimal_cluster_with_applications.py
> +  config: |
Please elaborate more. How can I know if something changed? In the case of previous modules terraform takes care of that. Here I don't have any checking code, I can't get "current" state of the Epiphany, we don't have such feature. :thinking:

2020-10-06 13:21 UTC, sk4zuzu commented on resources/azepi/apply.py
> +            "--vault-password=" + "'asd'",
Yes!

2020-10-06 14:32 UTC, mkyc commented on Dockerfile
> +FROM $ARG_BASE_IMAGE
yes it is, but for development purposes you can change it even directly in file ;) We should not allow different versions here. My opinion is that it should be dead clear what version I'm looking at right now.

2020-10-06 14:32 UTC, mkyc commented on Makefile
> +	cd $(CACHE_DIR)/epiphany/ && docker build -t epicli-$(IMAGE)-develop .
yes, can we rename it then to build-develop-epicli-image? or something more meaningful than `epicli`?

2020-10-06 14:34 UTC, mkyc commented on Makefile
> +	cd $(ROOT_DIR)/ && git diff
it is ok to install whatever you need to perform build step in build container. We don't want linter in final image, though.

2020-10-06 14:35 UTC, mkyc commented on README.md
> +```
It's not clear in description. Please make it clearer :)

2020-10-06 14:36 UTC, mkyc commented on README.md
> +```
Why would we need to rewrite it? As far as I understand, we want to have more steps in main Dockerfile and execute test operations there in build phase image definition.

2020-10-06 14:37 UTC, mkyc commented on README.md
> +```
Ah, yes. So please put it to develop or contribute section.

2020-10-06 14:38 UTC, mkyc commented on README.md
> +### Prepare service principal
yeah but using ### everywhere makes it flat. I believe from previous comments that we want to have `#howto` and `#contributing` sections and all stuff put as subsections `##....` inside.

2020-10-06 14:39 UTC, mkyc commented on README.md
> +In `examples/basic_flow` directory run (in order):
Yeah ..... I believe it's ok for now. Later we should have some more talk what does it mean to "destroy" in case of this module.

2020-10-06 14:46 UTC, mkyc commented on pylintrc
> +disable=print-statement,
where did you take it from? I found [this](https://github.com/PyCQA/pylint/blob/master/pylintrc#L56) in pylint master and it has much less disable rules.

2020-10-06 14:52 UTC, mkyc commented on tests/integration/test_plan_minimal_cluster_with_applications.py
> +  config: |
Ok, after extensive discussion we agreed that configuration can stay here. This module is generally not designed for production right now, so we do not need to polish it to that level.

2020-10-06 15:01 UTC, sk4zuzu commented on pylintrc
> +disable=print-statement,
pylint +
```    --generate-rcfile   Generate a sample configuration file according to the
                        current configuration. You can put other options
                        before this one to get them in the generated
                        configuration.
```
This is kinda weird. I'll prepare minimal config then. :+1:

2020-10-06 15:29 UTC, sk4zuzu commented on README.md
> +```
I removed it. Rationale is that developer will look inside the Makefile anyways :+1:

2020-10-06 15:30 UTC, sk4zuzu commented on README.md
> +![](https://i.imgur.com/pgkhdkK.png)
Removed it, we dont have to prove anything to anybody here. :hugs:

2020-10-06 16:32 UTC, sk4zuzu commented on resources/azepi/init.py
> +def _get_dummy_machines(_, count):
Corrected!

2020-10-06 16:34 UTC, sk4zuzu commented on resources/azepi/init.py
> +        machines = _get_dummy_machines(v, 4)
Modfied to be in sync with the initial config (set to "2"). Not the best solution, but this is not a production module anyways. :trollface:

2020-10-06 16:34 UTC, sk4zuzu commented on resources/azepi/init.py
> +    })
Fixed!

2020-10-06 16:35 UTC, sk4zuzu commented on resources/azepi/init.py
> +        del state[v["M_MODULE_SHORT"]]
I removed this code!

2020-10-06 16:48 UTC, sk4zuzu commented on resources/azepi/_helpers.py
> +def memoize(function):
I removed the function! :smile:

2020-10-06 17:11 UTC, sk4zuzu commented on resources/azepi/metadata.py
> +  kind: infrastructure
I changed it to "provisioner" in this commit https://github.com/sk4zuzu/m-classic-epiphany-on-aks/pull/1/commits/03e708b3a1973df3b5b0a61c84ea21839d5a7d3c
I hope this is ok - not resolving yet. :+1::innocent:

2020-10-06 17:29 UTC, sk4zuzu commented on resources/azepi/metadata.py
> +  kind: infrastructure
After brief discussion https://github.com/sk4zuzu/m-classic-epiphany-on-aks/pull/1/commits/0562e7ad1fb6862b420699d07827ee98126469ca :hand_over_mouth:

2020-10-06 18:17 UTC, sk4zuzu commented on resources/azepi/apply.py
> +            "--vault-password=" + "'asd'",
Added in this commit https://github.com/sk4zuzu/m-classic-epiphany-on-aks/pull/1/commits/c3889622f705a4df8b6d9e7f3669610569497410 :+1::innocent:

2020-10-06 18:32 UTC, sk4zuzu commented on resources/azepi/init.py
> +# Original one seems to be incorrect (05 Oct 2020)
Issue created https://github.com/epiphany-platform/epiphany/issues/1743 :thinking:

2020-10-06 19:29 UTC, sk4zuzu commented on resources/azepi/init.py
> +    })
I misunderstood initially the intention. All merged now! :hugs:

2020-10-06 19:30 UTC, sk4zuzu commented on resources/azepi/init.py
> +        machines = _get_dummy_machines(v, 4)
I pushed the correct fix! :hugs:

2020-10-06 20:12 UTC, mkyc commented
This is productive reviewing: 

![Screenshot 2020-10-06 at 22 11 32](https://user-images.githubusercontent.com/28505782/95254954-f9ed8280-0820-11eb-87c8-cd427e1ea31a.png)

❤️

2020-10-06 20:56 UTC, sk4zuzu commented on examples/basic_flow/Makefile
> +		kubeconfig
Fixed in https://github.com/sk4zuzu/m-classic-epiphany-on-aks/pull/1/commits/3f3486d04d81f85f789e1a0f6280e10f83e8d667 :+1::innocent:

2020-10-06 20:57 UTC, sk4zuzu commented on examples/basic_flow/Makefile
> +	@cp $(ROOT_DIR)/shared/kubeconfig $(ROOT_DIR)/shared/build/azepi/
Fixed in https://github.com/sk4zuzu/m-classic-epiphany-on-aks/pull/1/commits/3f3486d04d81f85f789e1a0f6280e10f83e8d667 :+1::innocent:

2020-10-07 07:35 UTC, sk4zuzu commented on README.md
> +```
Implemented! :smile:

2020-10-07 07:35 UTC, sk4zuzu commented on Makefile
> +	cd $(ROOT_DIR)/ && git diff
Implemented! :smile:

2020-10-07 08:14 UTC, sk4zuzu commented on Dockerfile
> +FROM $ARG_BASE_IMAGE
Done. I made it possible to pull the image or to build it from source. :+1::innocent:

2020-10-07 08:15 UTC, sk4zuzu commented on Makefile
> +	cd $(CACHE_DIR)/epiphany/ && docker build -t epicli-$(IMAGE)-develop .
Done. I made it possible to pull the image or to build it from source. :+1::innocent:
We have two makefile targets: epicli-pull and epicli-build. Readme mentions the first one. :)

2020-10-07 09:18 UTC, atsikham commented on tests/integration/test_plan_minimal_cluster_with_applications.py
> +  config: |
Is it a reason to create related task in the future?

2020-10-07 09:29 UTC, atsikham commented
After reviewing I feel that modules relationships are managed in a complex way somehow. Also some configs/templates are stored right in the code, I would place them to separate files inside resources folder or something like this.

2020-10-07 09:31 UTC, sk4zuzu commented on .dockerignore
> +/.pytest_cache/
The benefit here is that both dockerignore and gitignore are identical, just a practical choice (less work more time). :)

2020-10-07 09:33 UTC, sk4zuzu commented on resources/azepi/init.py
> +      machines: []
Not sure. It has never crossed my mind to ask that question to myself. I have to verify. :thinking:

2020-10-07 09:34 UTC, sk4zuzu commented on resources/azepi/init.py
> +  vault_password: "asd"
So after the init method is done, an user can edit the config and carry on with a different value. Also for the purpose of research it's not protected in anyway. :)

2020-10-07 09:49 UTC, sk4zuzu commented on resources/azepi/init.py
> +      machines: []
Removed! :)

2020-10-07 10:04 UTC, sk4zuzu commented
> After reviewing I feel that modules relationships are managed in a complex way somehow. Also some configs/templates are stored right in the code, I would place them to separate files inside resources folder or something like this.

Yes I think decoupling code and templates is the logical step forward! Not sure if we need it that much ATM. :thinking:

2020-10-07 12:55 UTC, sk4zuzu commented on .dockerignore
> +/.pytest_cache/
After some thought. Yes, defnitely it is better. :+1::heart_eyes:

2020-10-07 14:12 UTC, mkyc commented
During testing: 

```
make build

...

Step 27/32 : RUN : FIX ACCESS RIGHTS  && chown -R $HOST_UID:$HOST_GID     $M_WORKDIR/     $M_RESOURCES/     $M_TESTS/
 ---> Running in 06dd0beadbda
chown: invalid spec: ‘501:’
```

2020-10-07 15:01 UTC, sk4zuzu commented
> During testing:
> 
> ```
> make build
> 
> ...
> 
> Step 27/32 : RUN : FIX ACCESS RIGHTS  && chown -R $HOST_UID:$HOST_GID     $M_WORKDIR/     $M_RESOURCES/     $M_TESTS/
>  ---> Running in 06dd0beadbda
> chown: invalid spec: ‘501:’
> ```

https://github.com/sk4zuzu/m-classic-epiphany-on-aks/pull/1/commits/ca79cb0ff875b7e05ce94236c3060d442d058206 :vomiting_face: :hugs:

2020-10-12 11:55 UTC, mkyc commented on Makefile
> +BASE_IMAGE ?= epiphanyplatform/epicli:0.8.0-RC1
```suggestion
BASE_IMAGE ?= epiphanyplatform/epicli:0.8.0rc1
```

2020-10-12 13:44 UTC, mkyc commented
@sk4zuzu please make this one more change from my last comment

2020-10-12 13:57 UTC, mkyc approved these changes
LGTM

2020-10-12 14:03 UTC, merged